<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{3D Graphs}
-->
```{r include=FALSE}
library(rgl);library(knitr);render_html()
```
# 3d graphs #
This example is from [Yihui's response](http://stackoverflow.com/questions/14879210/including-a-interactive-3d-figure-with-knitr) to a stack overflow question.

Need to load the CanvasMatrix library and the hook_webgl code to get 3d graphs to work
```{r setup}
has_X11 = Sys.getenv('DISPLAY') != ""
if(has_X11)
  knit_hooks$set(webgl = hook_webgl)
```
```{html}
<script src="https://dl.dropbox.com/u/15335397/misc/CanvasMatrix.js"></script>
```
<script src="https://dl.dropbox.com/u/15335397/misc/CanvasMatrix.js"></script>

## point 3d graph ##
```{r 3d_points, webgl=TRUE, eval=has_X11}
x <- sort(rnorm(1000))
y <- rnorm(1000)
z <- rnorm(1000) + atan2(x, y)
plot3d(x, y, z, col = rainbow(1000))
```
## spheres 3d graph ##
```{r 3d_spheres, webgl=TRUE, eval=has_X11}
open3d()
spheres3d(x, y, z, col = rainbow(1000))
```

Author: [Jim Hester](http://jimhester.com)
Created: 2013 Mar 27 10:54:38 PM
Last Modified: 2013 Jun 12 02:40:33 PM
